# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: register.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import google.protobuf.descriptor_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='register.proto',
  package='',
  serialized_pb='\n\x0eregister.proto\x1a google/protobuf/descriptor.proto\"\xb2\x01\n\x11PBRegisterService\x12\r\n\x05major\x18\x14 \x02(\t\x12\r\n\x05minor\x18\x15 \x02(\t\x12/\n\tinterface\x18\x16 \x02(\x0e\x32\x1c.PBRegisterService.Interface\x12\x0c\n\x04host\x18\x18 \x01(\t\x12\x0b\n\x03url\x18\x1a \x03(\t\"3\n\tInterface\x12\x0b\n\x07PUBLISH\x10\x00\x12\x0c\n\x08SNAPSHOT\x10\x01\x12\x0b\n\x07\x43ONTROL\x10\x02')



_PBREGISTERSERVICE_INTERFACE = _descriptor.EnumDescriptor(
  name='Interface',
  full_name='PBRegisterService.Interface',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PUBLISH', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SNAPSHOT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONTROL', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=180,
  serialized_end=231,
)


_PBREGISTERSERVICE = _descriptor.Descriptor(
  name='PBRegisterService',
  full_name='PBRegisterService',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='major', full_name='PBRegisterService.major', index=0,
      number=20, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='minor', full_name='PBRegisterService.minor', index=1,
      number=21, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='interface', full_name='PBRegisterService.interface', index=2,
      number=22, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='host', full_name='PBRegisterService.host', index=3,
      number=24, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='url', full_name='PBRegisterService.url', index=4,
      number=26, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PBREGISTERSERVICE_INTERFACE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=53,
  serialized_end=231,
)

_PBREGISTERSERVICE.fields_by_name['interface'].enum_type = _PBREGISTERSERVICE_INTERFACE
_PBREGISTERSERVICE_INTERFACE.containing_type = _PBREGISTERSERVICE;
DESCRIPTOR.message_types_by_name['PBRegisterService'] = _PBREGISTERSERVICE

class PBRegisterService(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBREGISTERSERVICE

  # @@protoc_insertion_point(class_scope:PBRegisterService)


# @@protoc_insertion_point(module_scope)
